version: '3.9'

services:
  my-database:
    image: postgres:16
    restart: always
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  my-database-admin:
    image: dpage/pgadmin4:7.8
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
