export const NAV_LINKS = {
  ROOT: { ROUTE: '/', LABEL: 'Home' },
  REGISTER: { ROUTE: '/register', LABEL: 'Register' },
  LOGIN: { ROUTE: '/login', LABEL: 'Login' },
  SHOP: { ROUTE: '/shop', LABEL: 'Shop' },
  CART: { ROUTE: '/cart', LABEL: 'Cart' },
  USER_HISTORY: { ROUTE: '/user/history', LABEL: 'History' },
  USER_PASSWORD: { ROUTE: '/user/password', LABEL: 'Password' },
  USER_WISHLIST: { ROUTE: '/user/wishlist', LABEL: 'Wishlist' },
  ADMIN_DASHBOARD: { ROUTE: '/admin/dashboard', LABEL: 'History' },
  ADMIN_PRODUCT: { ROUTE: '/admin/product', LABEL: 'Product' },
  ADMIN_PRODUCTS: { ROUTE: '/admin/products', LABEL: 'Products' },
  ADMIN_CATEGORY: { ROUTE: '/admin/category', LABEL: 'Category' },
  ADMIN_SUBCATEGORY: { ROUTE: '/admin/subcategory', LABEL: 'Subcategory' },
  ADMIN_COUPON: { ROUTE: '/admin/coupon', LABEL: 'Coupon' },
};
