export const actionType = {
  API_CALL_START: 'API_CALL_START',
  API_CALL_SUCCESS: 'API_CALL_SUCCESS',
  API_CALL_FAIL: 'API_CALL_FAIL',
  API_CALL_RESET: 'API_CALL_RESET',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_CATEGORY: 'GET_CATEGORY',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
};
